name: Bug report
description: Report a very clearly broken issue.
body:
  - type: markdown
    attributes:
      value: |
        # osu! bug report

        Important to note that your issue may have already been reported before. Please check:
        - Pinned issues, at the top of https://github.com/ppy/osu/issues.
        - Current open `priority:0` issues, filterable [here](https://github.com/ppy/osu/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Apriority%3A0).
        - And most importantly, search for your issue both in the [issue listing](https://github.com/ppy/osu/issues) and the [Q&A discussion listing](https://github.com/ppy/osu/discussions/categories/q-a). If you find that it already exists, respond with a reaction or add any further information that may be helpful.

  - type: dropdown
    attributes:
      label: Type
      options:
        - Crash to desktop
        - Game behaviour
        - Performance
        - Cosmetic
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug description
      description: How did you find the bug? Any additional details that might help?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or videos
      description: Add screenshots or videos that show the bug here.
      placeholder: Drag and drop the screenshots/videos into this box.
    validations:
      required: false
  - type: input
    attributes:
      label: Version
      description: The version you encountered this bug on. This is shown at the bottom of the main menu and also at the end of the settings screen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Logs

        Attaching log files is required for every reported bug. See instructions below on how to find them.

        **Logs are reset when you reopen the game.** If the game crashed or has been closed since you found the bug, retrieve the logs using the file explorer instead.

        ### Desktop platforms

        If the game has not yet been closed since you found the bug:
          1. Head on to game settings and click on "Open osu! folder"
          2. Then open the `logs` folder located there

        The default places to find the logs on desktop platforms are as follows:
          - `%AppData%/osu/logs` *on Windows*
          - `~/.local/share/osu/logs` *on Linux*
          - `~/Library/Application Support/osu/logs` *on macOS*

        If you have selected a custom location for the game files, you can find the `logs` folder there.

        ### Mobile platforms

        The places to find the logs on mobile platforms are as follows:
          - *On Android*, navigate to `Android/data/sh.ppy.osulazer/files/logs` using a file browser app.
          - *On iOS*, connect your device to a PC and copy the `logs` directory from the app's document storage using iTunes. (https://support.apple.com/en-us/HT201301#copy-to-computer)

        ---

        After locating the `logs` folder, select all log files inside and drag them into the "Logs" box below.

  - type: textarea
    attributes:
      label: Logs
      placeholder: Drag and drop the log files into this box.
    validations:
      required: true
