name: Bug report
description: Report a very clearly broken issue.
body:
  - type: markdown
    attributes:
      value: |
        # osu! bug report

        Important to note that your issue may have already been reported before. Please check:
        - Pinned issues, at the top of https://github.com/ppy/osu/issues.
        - Current open `priority:0` issues, filterable [here](https://github.com/ppy/osu/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Apriority%3A0).
        - And most importantly, search for your issue both in the [issue listing](https://github.com/ppy/osu/issues) and the [Q&A discussion listing](https://github.com/ppy/osu/discussions/categories/q-a). If you find that it already exists, respond with a reaction or add any further information that may be helpful.

        # ATTENTION LINUX USERS

        If you are having an issue and it is hardware related, **please open a [q&a discussion](https://github.com/ppy/osu/discussions/categories/q-a)** instead of an issue. There's a high chance your issue is due to your system configuration, and not our software.

  - type: dropdown
    attributes:
      label: Type
      options:
        - Crash to desktop
        - Game behaviour
        - Performance
        - Cosmetic
        - Other
    validations:
      required: true
  - type: textarea
    attributes:
      label: Bug description
      description: How did you find the bug? Any additional details that might help?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots or videos
      description: Add screenshots or videos that show the bug here.
      placeholder: Drag and drop the screenshots/videos into this box.
    validations:
      required: false
  - type: input
    attributes:
      label: Version
      description: The version you encountered this bug on. This is shown at the end of the settings overlay.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Logs

        Attaching log files is required for **every** issue, regardless of whether you deem them required or not. See instructions below on how to find them.

        ### Desktop platforms

        If the game has not yet been closed since you found the bug:
          1. Head on to game settings and click on "Export logs"
          2. Click the notification to locate the file
          3. Drag the generated `.zip` files into the github issue window

        ![export logs button](https://github.com/ppy/osu/assets/191335/cbfa5550-b7ed-4c5c-8dd0-8b87cc90ad9b)

        ### Mobile platforms

        The places to find the logs on mobile platforms are as follows:
          - *On Android*, navigate to `Android/data/sh.ppy.osulazer/files/logs` using a file browser app.
          - *On iOS*, connect your device to a PC and copy the `logs` directory from the app's document storage using iTunes. (https://support.apple.com/en-us/HT201301#copy-to-computer)

  - type: textarea
    attributes:
      label: Logs
      placeholder: Drag and drop the log files into this box.
    validations:
      required: true
