blank_issues_enabled: false
contact_links:
    - name: Suggestions or feature request
      url: https://github.com/ppy/osu/discussions/categories/ideas
      about: Got something you think should change or be added? Search for or start a new discussion!
    - name: Help
      url: https://github.com/ppy/osu/discussions/categories/q-a
      about: osu! not working as you'd expect? Not sure it's a bug? Check the Q&A section!
    - name: osu!stable issues
      url: https://github.com/ppy/osu-stable-issues
      about: For osu!stable bugs (not osu!lazer), check out the dedicated repository. Note that we only accept serious bug reports.

